### ISSUE TITLE
Error When Running the Model with Default Settings

### ISSUE THREAD

**Issue by EngFatemeh** [feliperiosg/STORM2#1]
I tried to run the model with the example setting:

`python storm.py -w 2 -ps 0.2 0 -sf 0 0.1 `
, but I received this error:

<img width="960" alt="1" src="https://github.com/feliperiosg/STORM2/assets/101165513/0ddee587-b96f-4864-8032-cff7fb19f8e2">

So I ran it with default settings, and I received a new error that in line 588, the "MIN_RADIUS' is not defined: 
<img width="1419" alt="2" src="https://github.com/feliperiosg/STORM2/assets/101165513/f467c520-7a1c-422a-8596-978dcab230a5">

So I moved line 982 to line 580 to define "MIN_RADIUS" before the function:
<img width="751" alt="3" src="https://github.com/feliperiosg/STORM2/assets/101165513/41eec2a5-8b3e-4958-a2a7-d59db1677c16">
<img width="711" alt="4" src="https://github.com/feliperiosg/STORM2/assets/101165513/47ee3c44-c8f9-4069-9a75-a4080376ec25">

But I received a new error: TypeError: buffer) missing 1 required positional argument: 'distance'
<img width="1419" alt="5" src="https://github.com/feliperiosg/STORM2/assets/101165513/7f27e8cb-9d7f-4be7-9ab9-29fde0949297">

So I changed "resolution= .. " to "distance= .." :
<img width="743" alt="6" src="https://github.com/feliperiosg/STORM2/assets/101165513/5e7d5da8-0513-49f8-ad87-8a635bbfd574">

Now I am receiving another error:
<img width="1418" alt="7" src="https://github.com/feliperiosg/STORM2/assets/101165513/433cbf5d-904f-434d-be5e-8dd0b18c43a7">

Could you help me with this issue, please? Thank you. @feliperiosg @blissville71 

I am using Python 3.9.18 on Anaconda Navigator.

And I believe that I installed all the required packages:

pip list
Package                       Version
----------------------------- ------------
affine                        2.4.0
alabaster                     0.7.13
arrow                         1.3.0
astroid                       3.0.1
asttokens                     2.4.1
atomicwrites                  1.4.1
attrs                         23.1.0
autopep8                      2.0.4
Babel                         2.13.1
backports.functools-lru-cache 1.6.5
backports.zoneinfo            0.2.1
bcrypt                        4.0.1
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         23.10.1
bleach                        6.1.0
Brotli                        1.1.0
certifi                       2023.7.22
cffi                          1.16.0
cftime                        1.6.3
chardet                       5.2.0
charset-normalizer            3.3.2
Chunking                      0.0.2
click                         8.1.7
click-plugins                 1.1.1
cligj                         0.7.2
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.1.4
contourpy                     1.2.0
cookiecutter                  2.4.0
cryptography                  41.0.5
cycler                        0.12.1
DateTime                      5.2
debugpy                       1.8.0
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20230430
dill                          0.3.7
docstring-to-markdown         0.13
docutils                      0.20.1
entrypoints                   0.4
exceptiongroup                1.1.3
executing                     2.0.1
fastjsonschema                2.18.1
fiona                         1.9.5
flake8                        6.1.0
fonttools                     4.44.0
GDAL                          3.7.3
geopandas                     0.14.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.8.0
importlib-resources           6.1.1
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.26.0
ipython                       8.17.2
isort                         5.12.0
jaraco.classes                3.3.0
jedi                          0.18.2
jellyfish                     1.0.1
Jinja2                        3.1.2
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
jupyter_client                8.6.0
jupyter_core                  5.5.0
jupyterlab-pygments           0.2.2
keyring                       24.2.0
kiwisolver                    1.4.5
libpysal                      4.8.0
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.8.1
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.0
mistune                       3.0.2
more-itertools                10.1.0
mypy-extensions               1.0.0
nbclient                      0.8.0
nbconvert                     7.11.0
nbformat                      5.9.2
nest-asyncio                  1.5.8
netCDF4                       1.6.5
numpy                         1.26.0
numpydoc                      1.5.0
packaging                     23.2
pandas                        2.1.2
pandocfilters                 1.5.0
parameters                    0.2.1
paramiko                      3.3.1
parso                         0.8.3
pathspec                      0.11.2
patsy                         0.5.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        10.1.0
pip                           23.3.1
pkgutil_resolve_name          1.3.10
platformdirs                  3.11.0
pluggy                        1.3.0
ply                           3.11
pointpats                     2.4.0
prompt-toolkit                3.0.39
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycodestyle                   2.11.1
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      3.1.0
Pygments                      2.16.1
pylint                        3.0.2
pylint-venv                   3.0.3
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyparsing                     3.1.1
pyproj                        3.6.1
PyQt5                         5.15.9
PyQt5-sip                     12.12.2
PyQtWebEngine                 5.15.4
PySocks                       1.7.1
python-dateutil               2.8.2
python-lsp-black              1.3.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.9.0
python-slugify                8.0.1
pytoolconfig                  1.2.5
pytz                          2023.3.post1
pywin32                       306
pywin32-ctypes                0.2.2
PyYAML                        6.0.1
pyzmq                         25.1.1
QDarkStyle                    3.2
qstylizer                     0.2.2
QtAwesome                     1.2.3
qtconsole                     5.5.0
QtPy                          2.4.1
rasterio                      1.3.9
rasterstats                   0.19.0
referencing                   0.30.2
requests                      2.31.0
rich                          13.6.0
rope                          1.11.0
rpds-py                       0.12.0
Rtree                         1.1.0
scipy                         1.11.3
setuptools                    68.2.2
shapely                       2.0.2
simplejson                    3.19.2
sip                           6.7.12
six                           1.16.0
snowballstemmer               2.2.0
snuggs                        1.4.7
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        7.2.6
sphinxcontrib-applehelp       1.0.7
sphinxcontrib-devhelp         1.0.5
sphinxcontrib-htmlhelp        2.0.4
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.6
sphinxcontrib-serializinghtml 1.1.9
spyder                        5.5.0
spyder-kernels                2.5.0
stack-data                    0.6.2
statsmodels                   0.14.0
text-unidecode                1.3
textdistance                  4.5.0
three-merge                   0.1.1
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.12.2
tornado                       6.3.3
tqdm                          4.66.1
traitlets                     5.13.0
types-python-dateutil         2.8.19.14
typing_extensions             4.8.0
tzdata                        2023.3
ujson                         5.8.0
urllib3                       2.0.7
vonMisesMixtures              1.0.0
watchdog                      3.0.0
wcwidth                       0.2.9
webencodings                  0.5.1
whatthepatch                  1.0.5
wheel                         0.41.3
win-inet-pton                 1.1.0
xarray                        2023.10.1
yapf                          0.40.1
zipp                          3.17.0
zope.interface                6.1

**Comment by feliperiosg** [comment]
Dear @EngFatemeh,
Thanks for using our model.

STORM2 heavily relies on the file [parameters.py](https://github.com/feliperiosg/STORM2/blob/main/parameters.py). For any configuration, e.g., 1 or 2 seasons, you're encouraged to first set up this file to your ultimate purpose.
The reason you're having troubles in running ```python storm.py -w 2 -ps 0.2 0 -sf 0 0.1``` is because you're using by default a 1-season configuration, i.e., the following lines were/are active in the *parameters.py* file:
```
# PARAMETER   = [ S1 ]
PTOT_SC       = [0.00]
PTOT_SF       = [ 0.0]
STORMINESS_SC = [-0.0]
STORMINESS_SF = [+0.0]
```
Thus, when using the helpers **-ps** and **-sf**, STORM2 will argue that although you provide two values/seasons for each one of them, the other helpers **-pf** and **-ss** are only set up to 1 value/season.
Therefore you should either setup the *parameters.py* file to deal with two seasons, e.g., by activating the following lines (in *parameters.py*):
```
# PARAMETER   = [ S1 ,  S2 ]
PTOT_SC       = [ 0. , - .0]
PTOT_SF       = [+0.0, -0. ]
STORMINESS_SC = [ 0.0, + .0]
STORMINESS_SF = [-0.0,  0.0]
```
... or pass the following (full) description for dealing with 2 seasons ```python storm.py -w 2 -ps 0.2 0 -sf 0 0.1 -pf 0. .0 -ss 0 0``` (for instance). Bear in mind that even though you are passing a (full) 2-seasonal description in your input (from the command prompt), you might still have to alter the *parameters.py* file to change, e.g., the ```SEASONS_MONTHS``` parameter (something that it's not possible from the command prompt/line).
The input "helpers" are there just to facilitate some climatic runs after having set up (from *parameters.py*) the core of your model.

Sorry you had to put up with the ```MIN_RADIUS``` parameter. It was a product from an intermediate update to make ```RINGS_DIS``` dependant on the spatial resolution of the model. This issue has been now corrected in the current version (v.2.2.0).
Now, the parameter is called ```MINRADIUS``` (located in [parameters.py](https://github.com/feliperiosg/STORM2/blob/main/parameters.py)) and should not give you any more troubles (in principle... but please do let us know if otherwise).

Best,
